<?php

/**
 * @file
 */

/**
 * Constants
 */
defined('DLTS_INTERVIEW_PATH') or define('DLTS_INTERVIEW_PATH', drupal_get_path( 'module', 'dlts_interview') );

/**
 * Implement of hook_help().
 */
function dlts_interview_help( $path, $arg ) {
  switch ( $path ) {
    case 'admin/help#dlts_interview':
      $output = '';
      $output .= '<h3>' . t('Bitstream') . '</h3>';
      return $output;
  }
}

/**
 * Implements hook_menu().
 */
function dlts_interview_menu() {
  return array(
    'admin/config/bitstream/flowplayer' => array(
      'title' => 'Bitstream handling settings: Flowplayer',
      'description' => 'Set up Flowplayer',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('dlts_interview_player_flowplayer_config'),
      'access arguments' => array('access administration pages'),
      'file' => 'dlts_interview_admin.pages.inc',
    ),
  );
}

/**
 * Implements hook_theme().
 * This lets us tell Drupal about our theme functions and their arguments.
 */
function dlts_interview_theme() {
  return array(
    'dlts_interview_player_flowplayer_js' => array(
      'variables' => array(
        'player' => array(
          'url' => NULL,
          'flash' => array(),
          'theme' => NULL,
          'js_api' => NULL,
          'key' => NULL,
          'plugins ' => array(),
        ),
        'streams' => array(),
      ),
    ),
    'dlts_interview_html_player' => array(
      'variables' => array(
        'is_mobile' => FALSE,
        'is_tablet' => FALSE,
        'player' => array(
          'url' => NULL,
          'flash' => array(),
          'theme' => NULL,
          'js_api' => NULL,
          'key' => NULL,
          'plugins ' => array(),
        ),
        'streams' => array(),
      ),
    ),
    'dlts_interview_error' => array(
      'variables' => array(
        'msg' => NULL,
      ),
    )
  );
}

/**
 * Implements hook_node_view().
 * http://api.drupal.org/api/drupal/modules--node--node.module/function/node_view/7
 */
function dlts_interview_node_view( $node, $view_mode = 'full', $langcode = NULL ) {

  if (
	isset($node->field_playlist_ref)  // a playlist with a clip reference
	||
	isset($node->field_bitstream_ref) // a clip reference with a bitstream reference
	||
	isset($node->field_bitstream) // a bitstream
  ) {

    $detect = mobile_detect_get_object();

    $is_mobile = $detect->isMobile();

    $is_tablet = $detect->isTablet();

    if ( $is_mobile || $is_tablet ) {

      drupal_set_message('HTML video for you', 'status');

      // $markup = theme('dlts_interview_html_player', array());

    }

    elseif ( !$is_tablet && !$is_mobile ) {

      module_load_include('inc', 'dlts_interview', 'inc/flowplayer');

      preg_match( '/interview|clip|bitstream_set/', $node->type, $matches );

      $player = dlts_interview_flowplayer( $node, $matches[0] );

      $markup = theme('dlts_interview_player_flowplayer_js', $player);

    }

    else {

      $markup = theme('dlts_interview_error', array( 'msg' => t('Unable to initiate Flowplayer.') ) );

    }

    $node->content['dlts_interview_player_flowplayer'] = array( '#markup' => $markup, '#weight' => -1 );

  }

}

/**
 * Theme functions
 */
function theme_dlts_interview_player_flowplayer_js($variables) {

  drupal_add_css( libraries_get_path('flowplayer') . '/skin/minimalist.css', array( 'group' => CSS_DEFAULT, 'every_page' => TRUE ) );

  drupal_add_css( DLTS_INTERVIEW_PATH . '/css/dlts_interview.css', array( 'group' => CSS_DEFAULT, 'every_page' => TRUE ) );

  drupal_add_js( $variables['player']['js_api'] );

  drupal_add_js(
    array('dlts' =>
      array('interview' =>
        array( 'player' =>
          array(
            'url' => ( isset( $variables['player']['url'] ) ? $variables['player']['url'] : '' ),
            'key' => ( isset( $variables['player']['key'] ) ? $variables['player']['key'] : '' ),
            'plugins' => ( isset( $variables['player']['plugins'] ) ? $variables['player']['plugins'] : '' ),
            'flash' => array(
              'errorMessage' => $variables['player']['flash']['errorMessage'],
            ),
          ),
          'streams' => ( isset( $variables['streams'] ) ? $variables['streams'] : '' ),
        ),
      ),
    ),
    'setting'
  );
  drupal_add_js( DLTS_INTERVIEW_PATH . '/js/dlts_interview.js' );
  return '<div class="player flowplayer" id="'. $variables['streams'][0]['id'] .'"></div>';
}

function theme_dlts_interview_html_player($variables) {
  return '<div class="player html" id="'. $variables['streams'][0]['id'] .'"></div>';
}

function theme_dlts_interview_player_flowplayer_audio_clip( $variables ) {
  return '<div href="' . $variables['url'] . '" id="' . $variables['title'] . '">' . $variables['title'] . '</a>';
}

function theme_dlts_interview_error( $variables ) {
  return '<div class="dlts_interview flowplayer">'. $variables['msg'] .'</div>';
}

/*
 * @TODO: Find a better solution
 */

function theme_dlts_interview_player_flowplayer_playlist( $variables ) {
  drupal_add_css( libraries_get_path('flowplayer') . '/themes/playlist/default/playlist.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE ) );
  drupal_add_js( libraries_get_path('flowplayer') . '/plugins/js/flowplayer.playlist-3.0.8.min.js' );
  return array( t('default') => array(
      '#markup' => '<div class="playlist low"><a class="clip player">${title}<em>${duration}</em></a></div>',
    )
  );
}

function theme_dlts_interview_player_flowplayer_clip( $variables ) {
  return '<a class="clip player">${title}<em>${duration}</em></a>';
}